printWidth: 80
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
quoteProps: as-needed
trailingComma: none
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
singleAttributePerLine: true
overrides:
  - files:
      - "*.json"
    options:
      singleQuote: false
  - files:
      - "*.css"
      - "*.scss"
    options:
      singleQuote: false
